version: '3'
services:
  db:
    image: postgres:13.3-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./db-volume:/var/lib/postgresql/data
  web:
    build: .
    command: /bin/sh
    environment:
      WEBPACKER_DEV_SERVER_HOST: "0.0.0.0"
      RAILS_SERVE_STATIC_FILES: "1"
    volumes:
      - .:/apps/${APPLICATION_NAME}
    ports:
      - "3000:3000"
    depends_on:
      - db
    tty: true